name: "Build Test"

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        qt_version: [5.15.2]
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
        
    - name: Setup VS tools
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Install jom
      run: choco install jom

    - name: Run QMake
      run: |
        mkdir build
        cd build
        qmake ..\src\editorconfig-app\editorconfig-app.pro
        
    - name: Build
      run: |
        cd build
        jom
        
    - name: CMake Test
      run: |
        cd build
        cmake ..

    - name: CTest
      run: |
        cd build
        ctest -C Release -E braces_nested_start3 -E braces_nested_start4 -E braces_nested_end4 -E braces_nested_end5 -E braces_escaped_comma1 -E braces_patterns_nested2 -E braces_patterns_nested3 -E braces_patterns_nested5 -E braces_patterns_nested6 -E braces_patterns_nested8 -E braces_patterns_nested9 -E braces_numeric_range2 -E braces_numeric_range3 -E braces_numeric_range4 -E braces_numeric_range6 -E utf_8_char -E indent_size_default_pre_0_9_0 -E lowercase_values1_ML -E lowercase_values2_ML -E min_supported_key_length -E min_supported_value_length
